[profile.default]
solc_version = '0.8.25'
evm_version = 'cancun'
src = 'contracts'
out = "out"
libs = ["node_modules", "lib"]
test = 'test'
cache_path  = 'cache_forge'

remappings = [
  "@/contracts/=contracts/",
  "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
]

[profile.default.fuzz]
runs = 50

[profile.default.solc]
optimizer = true
optimizer_runs = 200
via_ir = true
